### ISSUE TITLE
List with multiple empty items overlaps with text after it

### ISSUE THREAD

**Issue by akishind-medlinx** [halilozercan/compose-richtext#150] opened 2024-12-05 08:56 UTC
If a list (ordered or unordered) contains many empty items, then it starts to overlap with content after it. For example,
```kotlin
Markdown(content ="1. \n2. \n3. \n4. \n5. \n6. \n7. \n\nSome text")
```
results in the following:

![image](https://github.com/user-attachments/assets/f21fac01-22d9-4ceb-9b29-dbbb53e4d5a7)

And each new empty line causes an even bigger overlap.

![image](https://github.com/user-attachments/assets/94057be3-6064-45d3-996d-408031b1ae19)

Of course, the list doesn't have to be all empty lines. If there are 30 items and 10 of them are empty, the result is the same.

Possibly relates to [this bug](https://github.com/halilozercan/compose-richtext/issues/96)

**Comment by halilozercan** [comment] 2024-12-06 01:46
Thanks for the report. The root cause was in the richtext-ui library, but markdown made it easy to notice. The fix should be merged into the next release that is 1.0.0-alpha02

**Closed as completed by halilozercan** 2024-12-06 01:46 UTC
